#!/bin/bash

# qemu-system-aarch64 -m 16384 -smp 8 -cpu host -M virt -M gic-version=3 --enable-kvm -nographic \
#   -drive if=pflash,file=files/flash0.img,format=raw \
#   -drive if=none,file=arm-sgo-2204/disk-image,id=hd0,format=raw \
#   -device virtio-blk-device,drive=hd0 \
#   -netdev user,id=eth0,hostfwd=tcp::6666-:22 \
#   -device virtio-net-device,netdev=eth0

qemu-system-aarch64 -m 16384 -smp 8 -cpu host -M virt -M gic-version=3 --enable-kvm -nographic \
-drive if=pflash,file=files/flash0.img,format=raw \
-drive if=none,file=arm-ubuntu-preload_MPI_OMP-2204/disk-image,id=hd0,format=raw \
-netdev user,id=net0 \
-device virtio-net-device,netdev=net0 \
-device virtio-blk-device,drive=hd0 \
-netdev user,id=eth0,hostfwd=tcp::7777-:22 \
-virtfs local,path=/home/wshaddix/Research/cxl_like_coherency/workloads/qemu-pipe,security_model=none,mount_tag=hostshare


qemu-system-aarch64 \
  -machine virt -cpu host -enable-kvm \
  -m 4G -smp 4 \
  -drive file=/home/wshaddix/Research/cxl_like_coherency/workloads/arm-ubuntu-dax-support-with-output-2204/disk-image,format=raw,if=virtio \
  -bios /usr/share/qemu-efi-aarch64/QEMU_EFI.fd \
  -device virtio-net-pci,netdev=net0 \
  -netdev user,id=net0 \
  -nographic